# -*- coding: utf-8 -*-
#
# Copyright (c) 2012-2015, CRS4
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

DATATYPES = {
    'ABSRANGE_1': ['sequence', None, 'RANGE', 'RANGE', None, -1],
    'ABSRANGE_2': ['leaf', None, 'NM', 'NUMERIC_CHANGE', None, -1],
    'ABSRANGE_3': ['leaf', None, 'NM', 'PERCENT_PER_CHANGE', None, -1],
    'ABSRANGE_4': ['leaf', None, 'NM', 'DAYS', None, -1],
    'ACCOUNTNO_1': ['leaf', None, 'NM', 'ACCOUNT_NUMBER', None, -1],
    'ACCOUNTNO_2': ['leaf', None, 'NM', 'CHECK_DIGIT', None, -1],
    'ACCOUNTNO_3': ['leaf', None, 'ID', 'CHECK_DIGIT_SCHEME', None, -1],
    'ACCOUNTNO_4': ['leaf', None, 'ID', 'FACILITY_ID', None, -1],
    'AD_1': ['leaf', None, 'ST', 'STREET_ADDRESS', None, -1],
    'AD_2': ['leaf', None, 'ST', 'OTHER_DESIGNATION', None, -1],
    'AD_3': ['leaf', None, 'ST', 'CITY', None, -1],
    'AD_4': ['leaf', None, 'ST', 'STATE_OR_PROVINCE', None, -1],
    'AD_5': ['leaf', None, 'ID', 'ZIP_OR_POSTAL_CODE', None, -1],
    'AD_6': ['leaf', None, 'ID', 'COUNTRY', None, -1],
    'AD_7': ['leaf', None, 'ID', 'TYPE', None, -1],
    'AD_8': ['leaf', None, 'ST', 'OTHER_GEOGRAPHIC_DESIGNATION', None, -1],
    'AUI_1': ['leaf', None, 'ST', 'AUTHORIZATION_NUMBER', None, -1],
    'AUI_2': ['leaf', None, 'DT', 'DATE', None, -1],
    'AUI_3': ['leaf', None, 'ST', 'SOURCE', None, -1],
    'BATCHTOTAL_1': ['leaf', None, 'NM', 'BATCH_TOTAL_1', None, -1],
    'BATCHTOTAL_2': ['leaf', None, 'NM', 'BATCH_TOTAL_2', None, -1],
    'CCD_1': ['leaf', None, 'ID', 'WHEN_TO_CHARGE', None, -1],
    'CCD_2': ['sequence', None, 'TS', 'DATE_TIME', None, -1],
    'CE_1': ['leaf', None, 'ID', 'IDENTIFIER', None, -1],
    'CE_2': ['leaf', None, 'ST', 'TEXT', None, -1],
    'CE_3': ['leaf', None, 'ST', 'NAME_OF_CODING_SYSTEM', None, -1],
    'CE_4': ['leaf', None, 'ST', 'ALTERNATE_IDENTIFIER', None, -1],
    'CE_5': ['leaf', None, 'ST', 'ALTERNATE_TEXT', None, -1],
    'CE_6': ['leaf', None, 'ST', 'NAME_OF_ALTERNATE_CODING_SYSTEM', None, -1],
    'CK_1': ['leaf', None, 'NM', 'ID_NUMBER', None, -1],
    'CK_2': ['leaf', None, 'NM', 'CHECK_DIGIT', None, -1],
    'CK_3': ['leaf', None, 'ID', 'CHECK_DIGIT_SCHEME', 'HL70061', -1],
    'CK_4': ['leaf', None, 'ST', 'ASSIGNING_FACILITY_ID', None, -1],
    'DDI_1': ['leaf', None, 'ST', 'DELAY_DAYS', None, -1],
    'DDI_2': ['leaf', None, 'NM', 'AMOUNT', None, -1],
    'DDI_3': ['leaf', None, 'NM', 'NUMBER_OF_DAYS', None, -1],
    'DIN_1': ['sequence', None, 'TS', 'DATE', None, -1],
    'DIN_2': ['sequence', None, 'CE', 'INSTITUTION_NAME', None, -1],
    'DLD_1': ['leaf', None, 'ID', 'DISCHARGE_LOCATION', None, -1],
    'DLD_2': ['sequence', None, 'TS', 'EFFECTIVE_DATE', None, -1],
    'DLT_1': ['sequence', None, 'RANGE', 'RANGE', None, -1],
    'DLT_2': ['leaf', None, 'NM', 'NUMERIC_THRESHOLD', None, -1],
    'DLT_3': ['leaf', None, 'ST', 'CHANGE', None, -1],
    'DLT_4': ['leaf', None, 'NM', 'LENGTH_OF_TIME_DAYS', None, -1],
    'DTN_1': ['leaf', None, 'ID', 'DAY_TYPE', None, -1],
    'DTN_2': ['leaf', None, 'NM', 'NUMBER_OF_DAYS', None, -1],
    'EIP_1': ['leaf', None, 'ST', 'PARENT_S_PLACER_ORDER_NUMBER', None, -1],
    'EIP_2': ['leaf', None, 'ST', 'PARENT_S_FILLER_ORDER_NUMBER', None, -1],
    'ELD_1': ['leaf', None, 'ST', 'SEGMENT_ID', None, -1],
    'ELD_2': ['leaf', None, 'NM', 'SEQUENCE', None, -1],
    'ELD_3': ['leaf', None, 'NM', 'FIELD_POSITION', None, -1],
    'ELD_4': ['sequence', None, 'CE', 'CODE_IDENTIFYING_ERROR', None, -1],
    'FILLER_1': ['leaf', None, 'ID', 'UNIQUE_FILLER_ID', None, -1],
    'FILLER_2': ['leaf', None, 'ID', 'FILLER_APPLICATION_ID', None, -1],
    'FINANCE_1': ['leaf', None, 'ID', 'FINANCIAL_CLASS_ID', None, -1],
    'FINANCE_2': ['sequence', None, 'TS', 'EFFECTIVE_DATE', None, -1],
    'GROUPID_1': ['leaf', None, 'ID', 'UNIQUE_GROUP_ID', None, -1],
    'GROUPID_2': ['leaf', None, 'ID', 'PLACER_APPLICATION_ID', None, -1],
    'INTERNALLOCATION_1': ['leaf', None, 'ID', 'NURSE_UNIT_STATION', None, -1],
    'INTERNALLOCATION_2': ['leaf', None, 'ID', 'ROOM', None, -1],
    'INTERNALLOCATION_3': ['leaf', None, 'ID', 'BED', None, -1],
    'INTERNALLOCATION_4': ['leaf', None, 'ID', 'FACILITY_ID', None, -1],
    'INTERNALLOCATION_5': ['leaf', None, 'ID', 'BED_STATUS', None, -1],
    'INTERNALLOCATION_6': ['leaf', None, 'ID', 'ETAGE', None, -1],
    'INTERNALLOCATION_7': ['leaf', None, 'ID', 'KLINIK', None, -1],
    'INTERNALLOCATION_8': ['leaf', None, 'ID', 'ZENTRUM', None, -1],
    'JOBCODE_1': ['leaf', None, 'ID', 'JOB_CODE', None, -1],
    'JOBCODE_2': ['leaf', None, 'ID', 'EMPLOYEE_CLASSIFICATION', None, -1],
    'LA1_1': ['sequence', None, 'INTERNALLOCATION', 'DISPENSE_DELIVER_TO_LOCATION', None, -1],
    'LA1_2': ['sequence', None, 'AD', 'LOCATION', None, -1],
    'LICENSENO_1': ['leaf', None, 'ST', 'LICENSE_NUMBER', None, -1],
    'LICENSENO_2': ['leaf', None, 'ST', 'ISSUING_STATE_PROVINCE_COUNTRY', None, -1],
    'MOC_1': ['leaf', None, 'ST', 'DOLLAR_AMOUNT', None, -1],
    'MOC_2': ['leaf', None, 'ST', 'CHARGE_CODE', None, -1],
    'MSG_1': ['leaf', None, 'ID', 'MESSAGE_TYPE', None, -1],
    'MSG_2': ['leaf', None, 'ID', 'TRIGGER_EVENT', None, -1],
    'NDL_1': ['sequence', None, 'PERSON', 'INTERPRETER_TECHNICIAN', None, -1],
    'NDL_2': ['sequence', None, 'TS', 'START_DATE_TIME', None, -1],
    'NDL_3': ['sequence', None, 'TS', 'END_DATE_TIME', None, -1],
    'NDL_4': ['sequence', None, 'INTERNALLOCATION', 'LOCATION', None, -1],
    'OCD_1': ['leaf', None, 'ID', 'OCCURRENCE_CODE', None, -1],
    'OCD_2': ['leaf', None, 'DT', 'OCCURRENCE_DATE', None, -1],
    'OSP_1': ['leaf', None, 'ID', 'OCCURRENCE_SPAN_CODE', None, -1],
    'OSP_2': ['leaf', None, 'DT', 'OCCURRENCE_SPAN_START_DATE', None, -1],
    'OSP_3': ['leaf', None, 'DT', 'OCCURRENCE_SPAN_STOP_DATE', None, -1],
    'PATID_1': ['leaf', None, 'ST', 'PATIENT_ID', None, -1],
    'PATID_2': ['leaf', None, 'NM', 'CHECK_DIGIT', None, -1],
    'PATID_3': ['leaf', None, 'ID', 'CHECK_DIGIT_SCHEME', None, -1],
    'PATID_4': ['leaf', None, 'ID', 'FACILITY_ID', None, -1],
    'PATID_5': ['leaf', None, 'ID', 'TYPE', None, -1],
    'PATID0192_1': ['leaf', None, 'ST', 'PATIENT_ID', None, -1],
    'PATID0192_2': ['leaf', None, 'NM', 'CHECK_DIGIT', None, -1],
    'PATID0192_3': ['leaf', None, 'ID', 'CHECK_DIGIT_SCHEME', None, -1],
    'PATID0192_4': ['leaf', None, 'ID', 'FACILITY_ID', None, -1],
    'PATID0192_5': ['leaf', None, 'ID', 'TYPE', 'HL70192', -1],
    'PCF_1': ['leaf', None, 'ID', 'PRE_CERTIFICATION_PATIENT_TYPE', None, -1],
    'PCF_2': ['leaf', None, 'ID', 'PRE_CERTICATION_REQUIRED', None, -1],
    'PCF_3': ['sequence', None, 'TS', 'PRE_CERTIFICATION_WINDOW', None, -1],
    'PEN_1': ['leaf', None, 'ID', 'PENALTY_ID', None, -1],
    'PEN_2': ['leaf', None, 'NM', 'PENALTY_AMOUNT', None, -1],
    'PERSON_1': ['leaf', None, 'ID', 'ID_NUMBER', None, -1],
    'PERSON_2': ['leaf', None, 'ST', 'FAMILIY_NAME', None, -1],
    'PERSON_3': ['leaf', None, 'ST', 'GIVEN_NAME', None, -1],
    'PERSON_4': ['leaf', None, 'ST', 'MIDDLE_INITIAL_OR_NAME', None, -1],
    'PERSON_5': ['leaf', None, 'ST', 'SUFFIX_E_G_JR_OR_III', None, -1],
    'PERSON_6': ['leaf', None, 'ST', 'PREFIX_E_G_DR', None, -1],
    'PERSON_7': ['leaf', None, 'ST', 'DEGREE_E_G_MD', None, -1],
    'PERSON_8': ['leaf', None, 'ID', 'SOURCE_TABLE_ID', None, -1],
    'PHYSICIAN_1': ['leaf', None, 'ID', 'PHYSICIAN_ID', None, -1],
    'PHYSICIAN_2': ['leaf', None, 'ST', 'FAMILIY_NAME', None, -1],
    'PHYSICIAN_3': ['leaf', None, 'ST', 'GIVEN_NAME', None, -1],
    'PHYSICIAN_4': ['leaf', None, 'ST', 'MIDDLE_INITIAL_OR_NAME', None, -1],
    'PHYSICIAN_5': ['leaf', None, 'ST', 'SUFFIX_E_G_JR_OR_III', None, -1],
    'PHYSICIAN_6': ['leaf', None, 'ST', 'PREFIX_E_G_DR', None, -1],
    'PHYSICIAN_7': ['leaf', None, 'ST', 'DEGREE_E_G_MD', None, -1],
    'PHYSICIAN_8': ['leaf', None, 'ID', 'SOURCE_TABLE_ID', None, -1],
    'PHYSICIAN_9': ['sequence', None, 'AD', 'ADRESSE', None, -1],
    'PHYSICIAN_10': ['leaf', None, 'TN', 'TELEFON', None, -1],
    'PHYSICIAN_11': ['leaf', None, 'TN', 'FAXNUMMER', None, -1],
    'PHYSICIAN_12': ['leaf', None, 'TN', 'ONLINE_NUMMER', None, -1],
    'PHYSICIAN_13': ['leaf', None, 'ST', 'E_MAIL', None, -1],
    'PIP_1': ['sequence', None, 'CE', 'PRIVILEGE', None, -1],
    'PIP_2': ['sequence', None, 'CE', 'PRIVILEGE_CLASS', None, -1],
    'PIP_3': ['leaf', None, 'DT', 'EXPIRATION_DATE', None, -1],
    'PIP_4': ['leaf', None, 'DT', 'ACTIVATION_DATE', None, -1],
    'PLACER_1': ['leaf', None, 'ID', 'UNIQUE_PLACER_ID', None, -1],
    'PLACER_2': ['leaf', None, 'ID', 'PLACER_APPLICATION', None, -1],
    'PLN_1': ['leaf', None, 'ST', 'ID_NUMBER', None, -1],
    'PLN_2': ['leaf', None, 'ID', 'TYPE_OF_ID_NUMBER_ID', None, -1],
    'PLN_3': ['leaf', None, 'ST', 'STATE_OTHER_QUALIFIYING_INFO', None, -1],
    'PN_1': ['leaf', None, 'ST', 'FAMILIY_NAME', None, -1],
    'PN_2': ['leaf', None, 'ST', 'GIVEN_NAME', None, -1],
    'PN_3': ['leaf', None, 'ST', 'MIDDLE_INITIAL_OR_NAME', None, -1],
    'PN_4': ['leaf', None, 'ST', 'SUFFIX_E_G_JR_OR_III', None, -1],
    'PN_5': ['leaf', None, 'ST', 'PREFIX_E_G_DR', None, -1],
    'PN_6': ['leaf', None, 'ST', 'DEGREE_E_G_MD', None, -1],
    'POSITION_1': ['leaf', None, 'ST', 'SAAL', None, -1],
    'POSITION_2': ['leaf', None, 'ST', 'TISCH', None, -1],
    'POSITION_3': ['leaf', None, 'ST', 'STUHL', None, -1],
    'PRACTITIONER_1': ['sequence', None, 'PERSON', 'PROCEDURE_PRACTITIONER_ID', None, -1],
    'PRACTITIONER_2': ['leaf', None, 'ID', 'PROCEDURE_PRACTITIONER_TYPE', None, -1],
    'PTA_1': ['leaf', None, 'ID', 'POLICY_TYPE', 'HL70147', -1],
    'PTA_2': ['leaf', None, 'ID', 'AMOUNT_CLASS', 'HL70193', -1],
    'PTA_3': ['leaf', None, 'NM', 'AMOUNT', None, -1],
    'QUANTITY_1': ['leaf', None, 'ST', 'QUANTITY', None, -1],
    'QUANTITY_2': ['leaf', None, 'ST', 'UNITS', None, -1],
    'RANGE_1': ['sequence', None, 'CE', 'LOW_VALUE', None, -1],
    'RANGE_2': ['sequence', None, 'CE', 'HIGH_VALUE', None, -1],
    'RFR_1': ['sequence', None, 'CE', 'REFERENCE_RANGE', None, -1],
    'RFR_2': ['leaf', None, 'ID', 'SEX', None, -1],
    'RFR_3': ['sequence', None, 'CE', 'AGE_RANGE', None, -1],
    'RFR_4': ['sequence', None, 'CE', 'GESTATIONAL_AGE_RANGE', None, -1],
    'RFR_5': ['leaf', None, 'ST', 'SPECIES', None, -1],
    'RFR_6': ['leaf', None, 'ID', 'RACE_SUBSPECIES', None, -1],
    'RFR_7': ['leaf', None, 'ST', 'TEXT_CONDITION', None, -1],
    'RI_1': ['leaf', None, 'ST', 'REPEAT_PATTERN', None, -1],
    'RI_2': ['leaf', None, 'ST', 'EXPLICIT_TIME_INTEVALL', None, -1],
    'RMC_1': ['leaf', None, 'ID', 'ROOM_TYPE', None, -1],
    'RMC_2': ['leaf', None, 'ID', 'AMOUNT_TYPE', None, -1],
    'RMC_3': ['leaf', None, 'NM', 'COVERAGE_AMOUNT', None, -1],
    'SPD_1': ['leaf', None, 'ST', 'SPECIALTY_NAME', None, -1],
    'SPD_2': ['leaf', None, 'ST', 'GOVERNING_BOARD', None, -1],
    'SPD_3': ['leaf', None, 'ID', 'ELIGIBLE_OR_CERTIFIED', None, -1],
    'SPD_4': ['leaf', None, 'DT', 'DATE_OF_CERTIFICATION', None, -1],
    'SPS_1': ['sequence', None, 'CE', 'SPECIMEN_SOURCE_NAME_OR_CODE', None, -1],
    'SPS_2': ['leaf', None, 'TX', 'ADDITIVES', None, -1],
    'SPS_3': ['leaf', None, 'TX', 'FREETEXT', None, -1],
    'SPS_4': ['sequence', None, 'CE', 'BODY_SITE', None, -1],
    'SPS_5': ['sequence', None, 'CE', 'SITE_MODIFIER', None, -1],
    'TQ_1': ['sequence', None, 'QUANTITY', 'QUANTITY', None, -1],
    'TQ_2': ['sequence', None, 'RI', 'INTERVAL', None, -1],
    'TQ_3': ['leaf', None, 'ST', 'DURATION', None, -1],
    'TQ_4': ['sequence', None, 'TS', 'START_DATE_TIME', None, -1],
    'TQ_5': ['sequence', None, 'TS', 'END_DATE_TIME', None, -1],
    'TQ_6': ['leaf', None, 'ID', 'PRIORITY', None, -1],
    'TQ_7': ['leaf', None, 'ST', 'CONDITION', None, -1],
    'TQ_8': ['leaf', None, 'TX', 'TEXT_TX', None, -1],
    'TQ_9': ['leaf', None, 'ID', 'CONJUNCTION', None, -1],
    'TQ_10': ['leaf', None, 'ST', 'ORDER_SEQUENCING', None, -1],
    'TS_1': ['leaf', None, 'ST', 'TIME_OF_AN_EVENT', None, -1],
    'TS_2': ['leaf', None, 'ST', 'DEGREE_OF_PRECISION', None, -1],
    'UVC_1': ['leaf', None, 'ID', 'VALUE_CODE', None, -1],
    'UVC_2': ['leaf', None, 'NM', 'VALUE_AMOUNT', None, -1],
    'VR_1': ['leaf', None, 'ST', 'FIRST_DATA_CODE_VALUE', None, -1],
    'VR_2': ['leaf', None, 'ST', 'LAST_DATA_CODE_CALUE', None, -1],
}


DATATYPES_STRUCTS = {
    'ABSRANGE': (
           ('ABSRANGE_1', DATATYPES['ABSRANGE_1'], (0, 1), 'CMP'),
           ('ABSRANGE_2', DATATYPES['ABSRANGE_2'], (0, 1), 'CMP'),
           ('ABSRANGE_3', DATATYPES['ABSRANGE_3'], (0, 1), 'CMP'),
           ('ABSRANGE_4', DATATYPES['ABSRANGE_4'], (0, 1), 'CMP'),),
    'ACCOUNTNO': (
           ('ACCOUNTNO_1', DATATYPES['ACCOUNTNO_1'], (0, 1), 'CMP'),
           ('ACCOUNTNO_2', DATATYPES['ACCOUNTNO_2'], (0, 1), 'CMP'),
           ('ACCOUNTNO_3', DATATYPES['ACCOUNTNO_3'], (0, 1), 'CMP'),
           ('ACCOUNTNO_4', DATATYPES['ACCOUNTNO_4'], (0, 1), 'CMP'),),
    'AD': (
           ('AD_1', DATATYPES['AD_1'], (0, 1), 'CMP'),
           ('AD_2', DATATYPES['AD_2'], (0, 1), 'CMP'),
           ('AD_3', DATATYPES['AD_3'], (0, 1), 'CMP'),
           ('AD_4', DATATYPES['AD_4'], (0, 1), 'CMP'),
           ('AD_5', DATATYPES['AD_5'], (0, 1), 'CMP'),
           ('AD_6', DATATYPES['AD_6'], (0, 1), 'CMP'),
           ('AD_7', DATATYPES['AD_7'], (0, 1), 'CMP'),
           ('AD_8', DATATYPES['AD_8'], (0, 1), 'CMP'),),
    'AUI': (
           ('AUI_1', DATATYPES['AUI_1'], (0, 1), 'CMP'),
           ('AUI_2', DATATYPES['AUI_2'], (0, 1), 'CMP'),
           ('AUI_3', DATATYPES['AUI_3'], (0, 1), 'CMP'),),
    'BATCHTOTAL': (
           ('BATCHTOTAL_1', DATATYPES['BATCHTOTAL_1'], (0, 1), 'CMP'),
           ('BATCHTOTAL_2', DATATYPES['BATCHTOTAL_2'], (0, 1), 'CMP'),),
    'CCD': (
           ('CCD_1', DATATYPES['CCD_1'], (0, 1), 'CMP'),
           ('CCD_2', DATATYPES['CCD_2'], (0, 1), 'CMP'),),
    'CE': (
           ('CE_1', DATATYPES['CE_1'], (0, 1), 'CMP'),
           ('CE_2', DATATYPES['CE_2'], (0, 1), 'CMP'),
           ('CE_3', DATATYPES['CE_3'], (0, 1), 'CMP'),
           ('CE_4', DATATYPES['CE_4'], (0, 1), 'CMP'),
           ('CE_5', DATATYPES['CE_5'], (0, 1), 'CMP'),
           ('CE_6', DATATYPES['CE_6'], (0, 1), 'CMP'),),
    'CK': (
           ('CK_1', DATATYPES['CK_1'], (0, 1), 'CMP'),
           ('CK_2', DATATYPES['CK_2'], (0, 1), 'CMP'),
           ('CK_3', DATATYPES['CK_3'], (0, 1), 'CMP'),
           ('CK_4', DATATYPES['CK_4'], (0, 1), 'CMP'),),
    'DDI': (
           ('DDI_1', DATATYPES['DDI_1'], (0, 1), 'CMP'),
           ('DDI_2', DATATYPES['DDI_2'], (0, 1), 'CMP'),
           ('DDI_3', DATATYPES['DDI_3'], (0, 1), 'CMP'),),
    'DIN': (
           ('DIN_1', DATATYPES['DIN_1'], (0, 1), 'CMP'),
           ('DIN_2', DATATYPES['DIN_2'], (0, 1), 'CMP'),),
    'DLD': (
           ('DLD_1', DATATYPES['DLD_1'], (0, 1), 'CMP'),
           ('DLD_2', DATATYPES['DLD_2'], (0, 1), 'CMP'),),
    'DLT': (
           ('DLT_1', DATATYPES['DLT_1'], (0, 1), 'CMP'),
           ('DLT_2', DATATYPES['DLT_2'], (0, 1), 'CMP'),
           ('DLT_3', DATATYPES['DLT_3'], (0, 1), 'CMP'),
           ('DLT_4', DATATYPES['DLT_4'], (0, 1), 'CMP'),),
    'DTN': (
           ('DTN_1', DATATYPES['DTN_1'], (0, 1), 'CMP'),
           ('DTN_2', DATATYPES['DTN_2'], (0, 1), 'CMP'),),
    'EIP': (
           ('EIP_1', DATATYPES['EIP_1'], (0, 1), 'CMP'),
           ('EIP_2', DATATYPES['EIP_2'], (0, 1), 'CMP'),),
    'ELD': (
           ('ELD_1', DATATYPES['ELD_1'], (0, 1), 'CMP'),
           ('ELD_2', DATATYPES['ELD_2'], (0, 1), 'CMP'),
           ('ELD_3', DATATYPES['ELD_3'], (0, 1), 'CMP'),
           ('ELD_4', DATATYPES['ELD_4'], (0, 1), 'CMP'),),
    'FILLER': (
           ('FILLER_1', DATATYPES['FILLER_1'], (0, 1), 'CMP'),
           ('FILLER_2', DATATYPES['FILLER_2'], (0, 1), 'CMP'),),
    'FINANCE': (
           ('FINANCE_1', DATATYPES['FINANCE_1'], (0, 1), 'CMP'),
           ('FINANCE_2', DATATYPES['FINANCE_2'], (0, 1), 'CMP'),),
    'GROUPID': (
           ('GROUPID_1', DATATYPES['GROUPID_1'], (0, 1), 'CMP'),
           ('GROUPID_2', DATATYPES['GROUPID_2'], (0, 1), 'CMP'),),
    'INTERNALLOCATION': (
           ('INTERNALLOCATION_1', DATATYPES['INTERNALLOCATION_1'], (0, 1), 'CMP'),
           ('INTERNALLOCATION_2', DATATYPES['INTERNALLOCATION_2'], (0, 1), 'CMP'),
           ('INTERNALLOCATION_3', DATATYPES['INTERNALLOCATION_3'], (0, 1), 'CMP'),
           ('INTERNALLOCATION_4', DATATYPES['INTERNALLOCATION_4'], (0, 1), 'CMP'),
           ('INTERNALLOCATION_5', DATATYPES['INTERNALLOCATION_5'], (0, 1), 'CMP'),
           ('INTERNALLOCATION_6', DATATYPES['INTERNALLOCATION_6'], (0, 1), 'CMP'),
           ('INTERNALLOCATION_7', DATATYPES['INTERNALLOCATION_7'], (0, 1), 'CMP'),
           ('INTERNALLOCATION_8', DATATYPES['INTERNALLOCATION_8'], (0, 1), 'CMP'),),
    'JOBCODE': (
           ('JOBCODE_1', DATATYPES['JOBCODE_1'], (0, 1), 'CMP'),
           ('JOBCODE_2', DATATYPES['JOBCODE_2'], (0, 1), 'CMP'),),
    'LA1': (
           ('LA1_1', DATATYPES['LA1_1'], (0, 1), 'CMP'),
           ('LA1_2', DATATYPES['LA1_2'], (0, 1), 'CMP'),),
    'LICENSENO': (
           ('LICENSENO_1', DATATYPES['LICENSENO_1'], (0, 1), 'CMP'),
           ('LICENSENO_2', DATATYPES['LICENSENO_2'], (0, 1), 'CMP'),),
    'MOC': (
           ('MOC_1', DATATYPES['MOC_1'], (0, 1), 'CMP'),
           ('MOC_2', DATATYPES['MOC_2'], (0, 1), 'CMP'),),
    'MSG': (
           ('MSG_1', DATATYPES['MSG_1'], (0, 1), 'CMP'),
           ('MSG_2', DATATYPES['MSG_2'], (0, 1), 'CMP'),),
    'NDL': (
           ('NDL_1', DATATYPES['NDL_1'], (0, 1), 'CMP'),
           ('NDL_2', DATATYPES['NDL_2'], (0, 1), 'CMP'),
           ('NDL_3', DATATYPES['NDL_3'], (0, 1), 'CMP'),
           ('NDL_4', DATATYPES['NDL_4'], (0, 1), 'CMP'),),
    'OCD': (
           ('OCD_1', DATATYPES['OCD_1'], (0, 1), 'CMP'),
           ('OCD_2', DATATYPES['OCD_2'], (0, 1), 'CMP'),),
    'OSP': (
           ('OSP_1', DATATYPES['OSP_1'], (0, 1), 'CMP'),
           ('OSP_2', DATATYPES['OSP_2'], (0, 1), 'CMP'),
           ('OSP_3', DATATYPES['OSP_3'], (0, 1), 'CMP'),),
    'PATID': (
           ('PATID_1', DATATYPES['PATID_1'], (0, 1), 'CMP'),
           ('PATID_2', DATATYPES['PATID_2'], (0, 1), 'CMP'),
           ('PATID_3', DATATYPES['PATID_3'], (0, 1), 'CMP'),
           ('PATID_4', DATATYPES['PATID_4'], (0, 1), 'CMP'),
           ('PATID_5', DATATYPES['PATID_5'], (0, 1), 'CMP'),),
    'PATID_0192': (
           ('PATID0192_1', DATATYPES['PATID0192_1'], (0, 1), 'CMP'),
           ('PATID0192_2', DATATYPES['PATID0192_2'], (0, 1), 'CMP'),
           ('PATID0192_3', DATATYPES['PATID0192_3'], (0, 1), 'CMP'),
           ('PATID0192_4', DATATYPES['PATID0192_4'], (0, 1), 'CMP'),
           ('PATID0192_5', DATATYPES['PATID0192_5'], (0, 1), 'CMP'),),
    'PCF': (
           ('PCF_1', DATATYPES['PCF_1'], (0, 1), 'CMP'),
           ('PCF_2', DATATYPES['PCF_2'], (0, 1), 'CMP'),
           ('PCF_3', DATATYPES['PCF_3'], (0, 1), 'CMP'),),
    'PEN': (
           ('PEN_1', DATATYPES['PEN_1'], (0, 1), 'CMP'),
           ('PEN_2', DATATYPES['PEN_2'], (0, 1), 'CMP'),),
    'PERSON': (
           ('PERSON_1', DATATYPES['PERSON_1'], (0, 1), 'CMP'),
           ('PERSON_2', DATATYPES['PERSON_2'], (0, 1), 'CMP'),
           ('PERSON_3', DATATYPES['PERSON_3'], (0, 1), 'CMP'),
           ('PERSON_4', DATATYPES['PERSON_4'], (0, 1), 'CMP'),
           ('PERSON_5', DATATYPES['PERSON_5'], (0, 1), 'CMP'),
           ('PERSON_6', DATATYPES['PERSON_6'], (0, 1), 'CMP'),
           ('PERSON_7', DATATYPES['PERSON_7'], (0, 1), 'CMP'),
           ('PERSON_8', DATATYPES['PERSON_8'], (0, 1), 'CMP'),),
    'PHYSICIAN': (
           ('PHYSICIAN_1', DATATYPES['PHYSICIAN_1'], (0, 1), 'CMP'),
           ('PHYSICIAN_2', DATATYPES['PHYSICIAN_2'], (0, 1), 'CMP'),
           ('PHYSICIAN_3', DATATYPES['PHYSICIAN_3'], (0, 1), 'CMP'),
           ('PHYSICIAN_4', DATATYPES['PHYSICIAN_4'], (0, 1), 'CMP'),
           ('PHYSICIAN_5', DATATYPES['PHYSICIAN_5'], (0, 1), 'CMP'),
           ('PHYSICIAN_6', DATATYPES['PHYSICIAN_6'], (0, 1), 'CMP'),
           ('PHYSICIAN_7', DATATYPES['PHYSICIAN_7'], (0, 1), 'CMP'),
           ('PHYSICIAN_8', DATATYPES['PHYSICIAN_8'], (0, 1), 'CMP'),
           ('PHYSICIAN_9', DATATYPES['PHYSICIAN_9'], (0, 1), 'CMP'),
           ('PHYSICIAN_10', DATATYPES['PHYSICIAN_10'], (0, 1), 'CMP'),
           ('PHYSICIAN_11', DATATYPES['PHYSICIAN_11'], (0, 1), 'CMP'),
           ('PHYSICIAN_12', DATATYPES['PHYSICIAN_12'], (0, 1), 'CMP'),
           ('PHYSICIAN_13', DATATYPES['PHYSICIAN_13'], (0, 1), 'CMP'),),
    'PIP': (
           ('PIP_1', DATATYPES['PIP_1'], (0, 1), 'CMP'),
           ('PIP_2', DATATYPES['PIP_2'], (0, 1), 'CMP'),
           ('PIP_3', DATATYPES['PIP_3'], (0, 1), 'CMP'),
           ('PIP_4', DATATYPES['PIP_4'], (0, 1), 'CMP'),),
    'PLACER': (
           ('PLACER_1', DATATYPES['PLACER_1'], (0, 1), 'CMP'),
           ('PLACER_2', DATATYPES['PLACER_2'], (0, 1), 'CMP'),),
    'PLN': (
           ('PLN_1', DATATYPES['PLN_1'], (0, 1), 'CMP'),
           ('PLN_2', DATATYPES['PLN_2'], (0, 1), 'CMP'),
           ('PLN_3', DATATYPES['PLN_3'], (0, 1), 'CMP'),),
    'PN': (
           ('PN_1', DATATYPES['PN_1'], (0, 1), 'CMP'),
           ('PN_2', DATATYPES['PN_2'], (0, 1), 'CMP'),
           ('PN_3', DATATYPES['PN_3'], (0, 1), 'CMP'),
           ('PN_4', DATATYPES['PN_4'], (0, 1), 'CMP'),
           ('PN_5', DATATYPES['PN_5'], (0, 1), 'CMP'),
           ('PN_6', DATATYPES['PN_6'], (0, 1), 'CMP'),),
    'POSITION': (
           ('POSITION_1', DATATYPES['POSITION_1'], (0, 1), 'CMP'),
           ('POSITION_2', DATATYPES['POSITION_2'], (0, 1), 'CMP'),
           ('POSITION_3', DATATYPES['POSITION_3'], (0, 1), 'CMP'),),
    'PRACTITIONER': (
           ('PRACTITIONER_1', DATATYPES['PRACTITIONER_1'], (0, 1), 'CMP'),
           ('PRACTITIONER_2', DATATYPES['PRACTITIONER_2'], (0, 1), 'CMP'),),
    'PTA': (
           ('PTA_1', DATATYPES['PTA_1'], (0, 1), 'CMP'),
           ('PTA_2', DATATYPES['PTA_2'], (0, 1), 'CMP'),
           ('PTA_3', DATATYPES['PTA_3'], (0, 1), 'CMP'),),
    'QUANTITY': (
           ('QUANTITY_1', DATATYPES['QUANTITY_1'], (0, 1), 'CMP'),
           ('QUANTITY_2', DATATYPES['QUANTITY_2'], (0, 1), 'CMP'),),
    'RANGE': (
           ('RANGE_1', DATATYPES['RANGE_1'], (0, 1), 'CMP'),
           ('RANGE_2', DATATYPES['RANGE_2'], (0, 1), 'CMP'),),
    'RFR': (
           ('RFR_1', DATATYPES['RFR_1'], (0, 1), 'CMP'),
           ('RFR_2', DATATYPES['RFR_2'], (0, 1), 'CMP'),
           ('RFR_3', DATATYPES['RFR_3'], (0, 1), 'CMP'),
           ('RFR_4', DATATYPES['RFR_4'], (0, 1), 'CMP'),
           ('RFR_5', DATATYPES['RFR_5'], (0, 1), 'CMP'),
           ('RFR_6', DATATYPES['RFR_6'], (0, 1), 'CMP'),
           ('RFR_7', DATATYPES['RFR_7'], (0, 1), 'CMP'),),
    'RI': (
           ('RI_1', DATATYPES['RI_1'], (0, 1), 'CMP'),
           ('RI_2', DATATYPES['RI_2'], (0, 1), 'CMP'),),
    'RMC': (
           ('RMC_1', DATATYPES['RMC_1'], (0, 1), 'CMP'),
           ('RMC_2', DATATYPES['RMC_2'], (0, 1), 'CMP'),
           ('RMC_3', DATATYPES['RMC_3'], (0, 1), 'CMP'),),
    'SPD': (
           ('SPD_1', DATATYPES['SPD_1'], (0, 1), 'CMP'),
           ('SPD_2', DATATYPES['SPD_2'], (0, 1), 'CMP'),
           ('SPD_3', DATATYPES['SPD_3'], (0, 1), 'CMP'),
           ('SPD_4', DATATYPES['SPD_4'], (0, 1), 'CMP'),),
    'SPS': (
           ('SPS_1', DATATYPES['SPS_1'], (0, 1), 'CMP'),
           ('SPS_2', DATATYPES['SPS_2'], (0, 1), 'CMP'),
           ('SPS_3', DATATYPES['SPS_3'], (0, 1), 'CMP'),
           ('SPS_4', DATATYPES['SPS_4'], (0, 1), 'CMP'),
           ('SPS_5', DATATYPES['SPS_5'], (0, 1), 'CMP'),),
    'TQ': (
           ('TQ_1', DATATYPES['TQ_1'], (0, 1), 'CMP'),
           ('TQ_2', DATATYPES['TQ_2'], (0, 1), 'CMP'),
           ('TQ_3', DATATYPES['TQ_3'], (0, 1), 'CMP'),
           ('TQ_4', DATATYPES['TQ_4'], (0, 1), 'CMP'),
           ('TQ_5', DATATYPES['TQ_5'], (0, 1), 'CMP'),
           ('TQ_6', DATATYPES['TQ_6'], (0, 1), 'CMP'),
           ('TQ_7', DATATYPES['TQ_7'], (0, 1), 'CMP'),
           ('TQ_8', DATATYPES['TQ_8'], (0, 1), 'CMP'),
           ('TQ_9', DATATYPES['TQ_9'], (0, 1), 'CMP'),
           ('TQ_10', DATATYPES['TQ_10'], (0, 1), 'CMP'),),
    'TS': (
           ('TS_1', DATATYPES['TS_1'], (0, 1), 'CMP'),
           ('TS_2', DATATYPES['TS_2'], (0, 1), 'CMP'),),
    'UVC': (
           ('UVC_1', DATATYPES['UVC_1'], (0, 1), 'CMP'),
           ('UVC_2', DATATYPES['UVC_2'], (0, 1), 'CMP'),),
    'VR': (
           ('VR_1', DATATYPES['VR_1'], (0, 1), 'CMP'),
           ('VR_2', DATATYPES['VR_2'], (0, 1), 'CMP'),),
}

for k, v in DATATYPES.iteritems():
    if v[0] == 'sequence':
        v[1] = DATATYPES_STRUCTS[v[2]]